IMP-281: Dominant-v2 proto
valitydev/damsel pull request #147
Opened 2024-08-01 22:48 UTC by ndiezel0

2024-08-02 10:29 UTC, WWWcool commented on proto/domain_config_v2.thrift
> +}
```suggestion
struct Head {}

typedef i64 Version
typedef i32 Limit

union VersionReference {
    1: Version version
    2: Head head
}

union ScopedReference {
    1: VersionReference global
    2: VersionReference local
}

union Version {
    1: Version global
    2: Version local
}
```

2024-08-09 07:13 UTC, nanodirijabl commented on proto/domain.thrift
> +    6  : PayoutMethod         payout_method
Надо будет выпилить. Пока не залил в дамзель (https://github.com/valitydev/damsel/pull/144), но пейаут объекты тут наверное стоило бы сразу исключить.

2025-03-05 08:13 UTC, A77AY commented on proto/domain.thrift
> + * - all types must be accounted in DOmainObjectTypes enum with
```suggestion
 * - all types must be accounted in DomainObjectTypes enum with
```

2025-04-14 19:50 UTC, A77AY requested changes

2025-04-14 19:50 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    2: required Version version
Было бы лучше сделать версию необязательной, чтобы не приходилось постоянно вызывать get latest ver

2025-04-14 19:50 UTC, A77AY commented on proto/domain_config_v2.thrift
> +}
А здесь возвращать версию

2025-04-14 19:57 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    1: required string query
выглядит слишком общим

2025-04-14 20:02 UTC, A77AY requested changes

2025-04-14 20:02 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    1: required string query
думаю должен быть необязательным, выглядит плохо, если я захочу просто получить объекты одного типа, например

2025-04-14 20:56 UTC, A77AY requested changes

2025-04-14 20:56 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    1: required list<VersionedObjectInfo> result
логично выглядит возвращать здесь VersionedObject или сделать два отдельных метода (в ref нет никакой информации чтобы хоть что то об объекте отобразить)

2025-04-15 12:48 UTC, ndiezel0 commented on proto/domain_config_v2.thrift
> +    2: required Version version
Хорошо

2025-04-15 13:02 UTC, ndiezel0 commented on proto/domain_config_v2.thrift
> +    1: required string query
Там содержится [tsquery](https://www.postgresql.org/docs/current/datatype-textsearch.html#DATATYPE-TSQUERY).

2025-04-15 13:36 UTC, ndiezel0 commented on proto/domain_config_v2.thrift
> +    1: required string query
Можешь просто передавать `*`. Это будет пропускать все содержимое

2025-04-15 13:39 UTC, ndiezel0 commented on proto/domain_config_v2.thrift
> +    1: required list<VersionedObjectInfo> result
В ref есть типы и id. Это сделано для того, чтобы не вываливать огромный массив данных, которые получились при поиске. Могу сделать отдельный метод, который будет выдавать полное содержимое каждого найденного объекта.

2025-04-15 14:51 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    1: required string query
ок, добавь плз коммент про tsquery

2025-04-15 14:52 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    1: required list<VersionedObjectInfo> result
да, нужен еще один метод

2025-04-15 14:54 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    1: required list<VersionedObjectInfo> result
было бы хорошо, если бы еще помимо ref, возвращал name и description

2025-04-15 19:09 UTC, ndiezel0 commented on proto/domain_config_v2.thrift
> +    1: required list<VersionedObjectInfo> result
name и description неполучится сделать для всех, он не у всех объектов есть, но я тебя понял, добавлю. Будет еще тогда метод типа FullSearch

2025-04-17 13:05 UTC, A77AY commented on proto/domain_config_v2.thrift
> +}
Для SearchObjects и SearchFullObjects разве не будет так, что у всех возвращаемых объектов будут одинаковые version, changed at, changed by?

2025-04-17 13:08 UTC, A77AY commented on proto/domain_config_v2.thrift
> +}
Если объекты имеют независимые версии, то тогда знать последнюю версию домена вообще перестает иметь смысл

2025-04-21 11:32 UTC, ndiezel0 commented on proto/domain_config_v2.thrift
> +}
Нет, версия отображаются по факту последнего изменения объекта.

2025-04-23 07:54 UTC, echerniak commented on proto/domain.thrift
> +enum DomainObjectTypes {
Мб `DomainObjectType`? s в наименовании подразумевает список, а тут просто тип же указан. Да и остальные енамы, которые смог рядом найти, называются без s в конце.

2025-04-23 08:07 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    2: required AuthorName name
@echerniak я хотел туда записывать email, тк это единственное уникальное поле которое я знаю, но предложили добавить get by email

2025-04-23 09:54 UTC, ndiezel0 commented on proto/domain.thrift
> +enum DomainObjectTypes {
Да, логично

2025-04-28 11:09 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    1: required string query
для остальных случаев по весу

2025-05-13 12:57 UTC, A77AY commented on proto/domain_config_v2.thrift
> +service RepositoryClient {
а есть сейчас какая то логика почему разделено на два сервиса Repository и RepositoryClient?

2025-05-13 15:13 UTC, A77AY requested changes

2025-05-13 15:13 UTC, A77AY commented on proto/domain_config_v2.thrift
> +}
Не хватает версии либо как раньше старого объекта чтобы избежать перезаписи

2025-05-13 15:25 UTC, A77AY commented on proto/domain_config_v2.thrift
> +}
выглядит так что ref должен быть в самом LimitedVersionedObject чтобы не дублировалось в VersionedObject

2025-05-13 15:32 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    3: optional string description
ну это может стать VersionedReference?

2025-05-13 17:39 UTC, ndiezel0 commented on proto/domain_config_v2.thrift
> +service RepositoryClient {
АПИ RepositoryClient важно для ядра и потому надо держать в стабильном состоянии. Но на самом деле какого-то великого смысла нет, кроме как референса к исторической практике

2025-05-13 17:40 UTC, ndiezel0 commented on proto/domain_config_v2.thrift
> +}
Когда ты делаешь Commit, у тебя есть версия на которую ты делаешь этот UpdateOp.

2025-05-13 17:43 UTC, ndiezel0 commented on proto/domain_config_v2.thrift
> +    3: optional string description
У тебя полный объект и так есть с этими полями. Зачем дублирование инфы?

2025-05-13 19:15 UTC, A77AY commented on proto/domain_config_v2.thrift
> +service RepositoryClient {
выглядит что он уже итак переписан и туда докинули еще один депрекейтед метод, как будто весь сервис депрекейтед, но просто repository не умеет checkout

2025-05-13 19:21 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    3: optional string description
хмм, просто у себя я сложнее мапил, например для валюты
<img width="271" alt="Screenshot 2025-05-14 at 00 20 33" src="https://github.com/user-attachments/assets/b60766f0-fe8f-4df1-9c0b-ab8b6e19ab96" />

2025-05-13 19:24 UTC, A77AY commented on proto/domain_config_v2.thrift
> +    3: optional string description
у меня был для пары объектов отдельный маппинг, но я глянул возможно это излишне

2025-05-13 19:25 UTC, A77AY commented on proto/domain_config_v2.thrift
> +}
считаю что это лучшее изменение

2025-05-19 11:06 UTC, WWWcool approved these changes

2025-05-19 11:07 UTC, A77AY approved these changes

2025-05-19 11:09 UTC, merged