IMP-76: Add new info
valitydev/damsel pull request #91
Opened 2023-09-06 11:07 UTC by WWWcool

2023-09-06 13:03 UTC, D-Baykov approved these changes

2023-09-07 04:15 UTC, tolkonepiu approved these changes

2023-09-07 04:26 UTC, tolkonepiu requested changes

2023-09-07 04:26 UTC, tolkonepiu commented on proto/domain.thrift
> +    9: optional string zip_code
Тут лучше postal_code

2023-09-07 09:51 UTC, tolkonepiu approved these changes

2023-09-07 09:52 UTC, merged